# Artificial Neural Network

### Importing the libraries

In [15]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os

In [16]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [22]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [23]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [29]:
### Splitting the dataset into the Training set and Test set

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [30]:
ann = tf.ann = tf.keras.models.Sequential()

2022-01-17 21:41:12.421423: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-17 21:41:12.421461: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-17 21:41:12.421494: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (brom-G2): /proc/driver/nvidia/version does not exist
2022-01-17 21:41:12.422834: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Adding the input layer and the first hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [33]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [34]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [39]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)

Epoch 1/200
240/240 [==============================] - 1s 3ms/step - loss: 26.1409
Epoch 2/200
240/240 [==============================] - 1s 2ms/step - loss: 26.7181
Epoch 3/200
240/240 [==============================] - 0s 2ms/step - loss: 26.5709
Epoch 4/200
240/240 [==============================] - 1s 2ms/step - loss: 26.6724
Epoch 5/200
240/240 [==============================] - 0s 2ms/step - loss: 26.6098
Epoch 6/200
240/240 [==============================] - 1s 2ms/step - loss: 26.5712
Epoch 7/200
240/240 [==============================] - 0s 2ms/step - loss: 26.4919
Epoch 8/200
240/240 [==============================] - 0s 2ms/step - loss: 26.3864
Epoch 9/200
240/240 [==============================] - 0s 2ms/step - loss: 26.7335
Epoch 10/200
240/240 [==============================] - 1s 2ms/step - loss: 26.7969
Epoch 11/200
240/240 [==============================] - 1s 2ms/step - loss: 26.8085
Epoch 12/200
240/240 [==============================] - 1s 2ms/step - loss: 26.9000
E

### Predicting the results of the Test set

In [40]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.45 431.23]
 [462.38 460.01]
 [465.84 461.14]
 ...
 [473.12 473.26]
 [439.94 438.  ]
 [459.13 463.28]]
